# Generated by Django 4.0.4 on 2022-05-10 12:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
